# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomClassBasedComponents' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CustomClassBasedComponents

  target 'CustomClassBasedComponentsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CustomClassBasedComponents-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CustomClassBasedComponents-tvOS

  target 'CustomClassBasedComponents-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
